on:
  push:
    branches:
      - master
  pull_request:

name: Test

jobs:
  check:
    strategy:
      matrix:
        os: ["ubuntu-18.04"]
        include:
          - os: ubuntu-18.04
            cran: https://demo.rstudiopm.com/all/__linux__/bionic/latest
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    timeout-minutes: 20
    env:
      CRAN: ${{ matrix.cran }}
      TEST_RSCONNECT_APIS: ${{ secrets.TEST_RSCONNECT_APIS }}
      TEST_RSCONNECT_SERVERS: ${{ secrets.TEST_RSCONNECT_SERVERS }}
      TEST_AWS_BUCKET: "pins-github-tests"
      TEST_AWS_KEY: "AKIAWDFKE5M2ZHDUORMW"
      TEST_AWS_REGION: "us-east-2"
      TEST_AWS_SECRET: ${{ secrets.TEST_AWS_SECRET }}
      TEST_GITHUB_REPO: "testme42"
      TEST_GITHUB_BRANCH: "ghtests"
      GITHUB_PAT: ${{ secrets.TEST_GITHUB_PAT }}
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: Rscript -e 'install.packages("remotes")' -e 'remotes::install_deps(dependencies = TRUE)'
      - name: Build and Test
        run: |
          R CMD build --resave-data --no-build-vignettes .
          R CMD check --no-manual --ignore-vignettes --no-tests pins*tar.gz
          Rscript ci/travis.R
